services:
  - type: web
    name: applepay-adyen-sample-full
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: ADYEN_API_KEY
        fromService: ""
      - key: ADYEN_MERCHANT_ACCOUNT
        fromService: ""
